// Tabela 24 do eSocial - Agentes Nocivos (amostra representativa)
export interface EsocialAgente {
  codigo: string;
  descricao: string;
}

export const esocialAgentes: EsocialAgente[] = [
  { codigo: "01.01.001", descricao: "Arsênio e seus compostos" },
  { codigo: "01.01.002", descricao: "Asbesto (amianto)" },
  { codigo: "01.01.003", descricao: "Benzeno" },
  { codigo: "01.01.004", descricao: "Berílio e seus compostos" },
  { codigo: "01.01.005", descricao: "Bromo" },
  { codigo: "01.01.006", descricao: "Cádmio e seus compostos" },
  { codigo: "01.01.007", descricao: "Carvão mineral e seus derivados" },
  { codigo: "01.01.008", descricao: "Chumbo e seus compostos" },
  { codigo: "01.01.009", descricao: "Cloro" },
  { codigo: "01.01.010", descricao: "Cromo e seus compostos" },
  { codigo: "01.01.011", descricao: "Dissulfeto de carbono" },
  { codigo: "01.01.012", descricao: "Fósforo e seus compostos" },
  { codigo: "01.01.013", descricao: "Hidrocarbonetos e outros compostos de carbono" },
  { codigo: "01.01.014", descricao: "Manganês e seus compostos" },
  { codigo: "01.01.015", descricao: "Mercúrio e seus compostos" },
  { codigo: "01.01.016", descricao: "Metais pesados (outros)" },
  { codigo: "01.01.017", descricao: "Névoas, gases e vapores" },
  { codigo: "01.01.018", descricao: "Sílica livre cristalizada" },
  { codigo: "01.01.019", descricao: "Substâncias cancerígenas" },
  { codigo: "01.01.020", descricao: "Poeiras minerais" },
  { codigo: "01.02.001", descricao: "Iodo" },
  { codigo: "01.02.002", descricao: "Níquel e seus compostos" },
  { codigo: "01.02.003", descricao: "Ácido crômico e cromatos" },
  { codigo: "01.02.004", descricao: "Ácido fluorídrico e fluoretos" },
  { codigo: "01.02.005", descricao: "Álcalis cáusticos" },
  { codigo: "01.03.001", descricao: "Petróleo, xisto betuminoso, gás natural e derivados" },
  { codigo: "01.04.001", descricao: "Agrotóxicos clorados e organofosforados" },
  { codigo: "01.04.002", descricao: "Agrotóxicos halogenados" },
  { codigo: "01.05.001", descricao: "Tintas, vernizes, solventes e pigmentos à base de compostos" },
  { codigo: "02.01.001", descricao: "Ruído contínuo ou intermitente" },
  { codigo: "02.01.002", descricao: "Ruído de impacto" },
  { codigo: "02.01.003", descricao: "Exposição ao calor" },
  { codigo: "02.01.004", descricao: "Exposição ao frio" },
  { codigo: "02.01.005", descricao: "Umidade" },
  { codigo: "02.01.006", descricao: "Vibração localizada (mãos e braços)" },
  { codigo: "02.01.007", descricao: "Vibração de corpo inteiro" },
  { codigo: "02.01.008", descricao: "Radiações ionizantes" },
  { codigo: "02.01.009", descricao: "Radiações não ionizantes" },
  { codigo: "02.01.010", descricao: "Pressões hiperbáricas" },
  { codigo: "02.01.011", descricao: "Pressões hipobáricas" },
  { codigo: "02.01.012", descricao: "Infrassom" },
  { codigo: "02.01.013", descricao: "Ultrassom" },
  { codigo: "03.01.001", descricao: "Microorganismos e parasitas infecciosos vivos e suas toxinas" },
  { codigo: "03.01.002", descricao: "Trabalho em contato com pacientes ou materiais infectocontagiosos" },
  { codigo: "03.01.003", descricao: "Trabalho com animais infectados" },
  { codigo: "03.01.004", descricao: "Trabalho em laboratórios de análises clínicas e pesquisa" },
  { codigo: "04.01.001", descricao: "Trabalho sob condições hiperbáricas" },
  { codigo: "04.01.002", descricao: "Trabalho em eletricidade (alta tensão)" },
  { codigo: "05.01.001", descricao: "Ausência de agente nocivo / Fator de risco" },
];
